# Generated by Django 6.0.2 on 2026-03-18 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_initial'),
        ('properties', '0002_property_code_alter_property_property_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='locations.district'),
        ),
    ]
