# Generated by Django 6.0.2 on 2026-03-18 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyspecs',
            name='area_unit',
            field=models.CharField(blank=True, choices=[('m2', 'Metros cuadrados'), ('ha', 'Hectareas'), ('m', 'm'), ('ft', 'ft')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='propertyspecs',
            name='garage_type',
            field=models.CharField(blank=True, choices=[('LINEAR_OPEN', 'Lineal Abierto'), ('ROOFED_LINEAR', 'Linear Techado'), ('PARALLEL_OPEN', 'Paralelo Abierto'), ('PARALLEL_ROOFED', 'Paralelo Techado'), ('OTHER', 'Otros')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propertyspecs',
            name='linear_unit',
            field=models.CharField(blank=True, choices=[('m2', 'Metros cuadrados'), ('ha', 'Hectareas'), ('m', 'm'), ('ft', 'ft')], max_length=10, null=True),
        ),
    ]
