# Generated by Django 6.0.2 on 2026-03-19 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_currency_symbol_propertycondition'),
        ('properties', '0004_alter_propertyspecs_area_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='property_documents', to='catalogs.documenttype'),
        ),
    ]
