# Generated by Django 6.0.2 on 2026-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_propertydocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfinancialinfo',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('exclusive', 'Exclusivo'), ('semi_exclusive', 'Semi exclusivo'), ('non_exclusive', 'No exclusivo')], max_length=30, null=True),
        ),
    ]
