# Generated by Django 6.0.2 on 2026-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_propertyfinancialinfo_contract_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
