# Generated by Django 6.0.2 on 2026-02-25 17:29

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'canal_lead',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'currency',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=140)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'document_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'event_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'lead_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'operation_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'payment_method',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'property_status',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertySubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'property_subtype',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'property_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UtilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('category', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'utility_service',
                'ordering': ['category', 'name'],
            },
        ),
    ]
