# Generated by Django 6.0.2 on 2026-03-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
