# Generated by Django 6.0.2 on 2026-03-16 18:00

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0003_alter_currency_symbol_propertycondition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('rate_date', models.DateTimeField(db_index=True)),
                ('provider', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'exchange_rate',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('source_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_entry', models.DateTimeField(blank=True, null=True)),
                ('id_chatwoot', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('date_last_message', models.DateTimeField(blank=True, null=True)),
                ('user_last_message', models.CharField(blank=True, choices=[('bot', 'Bot'), ('agent', 'Agent'), ('lead', 'Lead')], max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'lead',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('match_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], db_index=True, default='draft', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('response_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proposal',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('antiquity_years_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('antiquity_years_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('floors_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('floors_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bedrooms_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bathrooms_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bathrooms_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garage_spaces_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('garage_spaces_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('land_area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_area_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('built_area_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('has_elevator', models.BooleanField(blank=True, null=True)),
                ('pet_friendly', models.BooleanField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source_group', models.CharField(blank=True, max_length=150, null=True)),
                ('source_date', models.DateField(blank=True, null=True)),
                ('notes_message_ws', models.TextField(blank=True, null=True)),
                ('import_batch', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('import_row_sig', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'requirement',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RequirementMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('computed_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'requirement_match',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('full_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(blank=True, choices=[('dni', 'DNI'), ('passport', 'Passport'), ('ce', 'Carnet de extranjería')], max_length=20, null=True)),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='contacts/photos/')),
                ('contact_type', models.CharField(choices=[('owner', 'Owner'), ('interested', 'Interested'), ('other', 'Other')], default='other', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contact',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('tracing', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalogs.eventtype')),
            ],
            options={
                'db_table': 'event',
                'ordering': ['-start_time'],
            },
        ),
    ]
