# Generated by Django 6.0.2 on 2026-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_options_remove_contact_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
