# Generated by Django 6.0.2 on 2026-03-19 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_currency_symbol_propertycondition'),
        ('crm', '0004_lead_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='canal_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='catalogs.canallead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='catalogs.leadstatus'),
        ),
    ]
