# Generated by Django 6.0.2 on 2026-03-19 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_alter_currency_symbol_propertycondition'),
        ('crm', '0006_alter_event_code_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='catalogs.eventtype'),
        ),
    ]
