# Generated by Django 6.0.2 on 2026-04-01 17:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_event_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='assigned_agent',
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_agent',
            field=models.ManyToManyField(blank=True, null=True, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
