# Generated by Django 6.0.2 on 2026-04-01 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_contact_assigned_agent_contact_assigned_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='assigned_agent',
            field=models.ManyToManyField(blank=True, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
