# Generated by Django 6.0.2 on 2026-04-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
